function filterData=determine_and_filter(originalData)

Fs=2000;
freqGraph=figure;
plot_fftshift(originalData,Fs);

disp('determin Fstop')
[Fpass y]=ginput;
disp('Fstop = ');
Fpass
disp('determine Fpass');
[Fstop y]=ginput;
disp('Fpass = ');
Fstop
clear y;

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 04-Jun-2014 12:37:48

% Chebyshev Type II Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.

Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);
% [EOF]

% filtering
filterData=filter(Hd,originalData);